name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

env:
  default_php: 8.2

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
